INSERT INTO
    PASSAGEIROS(
                CPF,
                NOME,
                DATA_DE_NASCIMENTO,
                CLASSIFICACAO,
                MILHAS
) VALUES (
          '000.000.000-00',
          'Rachel Green',
          '1969-01-11',
          'VIP',
          100
         );

INSERT INTO
    PASSAGEIROS(
    CPF,
    NOME,
    DATA_DE_NASCIMENTO,
    CLASSIFICACAO,
    MILHAS
) VALUES (
             '111.111.111-11',
             'Phoebe Buffay',
             '1963-07-30',
             'OURO',
             100
         );

INSERT INTO
    PASSAGEIROS(
    CPF,
    NOME,
    DATA_DE_NASCIMENTO,
    CLASSIFICACAO,
    MILHAS
) VALUES (
             '222.222.222-22',
             'Ross Geller',
             '1966-11-02',
             'PRATA',
             100
         );

INSERT INTO
    PASSAGEIROS(
    CPF,
    NOME,
    DATA_DE_NASCIMENTO,
    CLASSIFICACAO,
    MILHAS
) VALUES (
             '333.333.333-33',
             'Monica Geller',
             '1964-06-15',
             'OURO',
             100
         );

INSERT INTO
    PASSAGEIROS(
    CPF,
    NOME,
    DATA_DE_NASCIMENTO,
    CLASSIFICACAO,
    MILHAS
) VALUES (
             '444.444.444-44',
             'Chandler Bing',
             '1969-08-19',
             'OURO',
             100
         );

INSERT INTO
    PASSAGEIROS(
    CPF,
    NOME,
    DATA_DE_NASCIMENTO,
    CLASSIFICACAO,
    MILHAS
) VALUES (
             '555.555.555-55',
             'Joey Tribbiani',
             '1967-07-25',
             'BRONZE',
             100
         );

INSERT INTO
    PASSAGEIROS(
    CPF,
    NOME,
    DATA_DE_NASCIMENTO,
    CLASSIFICACAO,
    MILHAS
) VALUES (
             '666.666.666-66',
             'Mike Hannigan',
             '1969-04-06',
             'VIP',
             100
         );

INSERT INTO
    PASSAGEIROS(
    CPF,
    NOME,
    DATA_DE_NASCIMENTO,
    CLASSIFICACAO,
    MILHAS
) VALUES (
             '777.777.777-77',
             'Gunther Tyler',
             '1962-05-28',
             'ASSOCIADO',
             100
         );

INSERT INTO
    PASSAGEIROS(
    CPF,
    NOME,
    DATA_DE_NASCIMENTO,
    CLASSIFICACAO,
    MILHAS
) VALUES (
             '888.888.888-88',
             'Janice Wheeler',
             '1961-08-07',
             'BRONZE',
             75
         );

INSERT INTO
    PASSAGEIROS(
    CPF,
    NOME,
    DATA_DE_NASCIMENTO,
    CLASSIFICACAO,
    MILHAS
) VALUES (
             '999.999.999-99',
             'Richard Burke',
             '1945-01-29',
             'BRONZE',
             50
         );

--Assentos--

INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('1A', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('1B', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('1C', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('1D', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('1E', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('1F', 0);

INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('2A', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('2B', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('2C', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('2D', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('2E', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('2F', 0);

INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('3A', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('3B', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('3C', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('3D', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('3E', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('3F', 0);

INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('3A', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('3B', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('3C', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('3D', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('3E', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('3F', 0);

INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('4A', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('4B', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('4C', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('4D', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('4E', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('4F', 0);

INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('5A', 1);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('5B', 1);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('5C', 1);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('5D', 1);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('5E', 1);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('5F', 1);

INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('6A', 1);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('6B', 1);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('6C', 1);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('6D', 1);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('6E', 1);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('6F', 1);

INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('7A', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('7B', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('7C', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('7D', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('7E', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('7F', 0);

INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('8A', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('8B', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('8C', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('8D', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('8E', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('8F', 0);

INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('9A', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('9B', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('9C', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('9D', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('9E', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('9F', 0);

INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('10A', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('10B', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('10C', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('10D', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('10E', 0);
INSERT INTO ASSENTOS(ASSENTO, FILEIRA_DE_EMERGENCIA) VALUES ('10F', 0);